on:
  push:
    branches:    
      - master
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
        
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    
    - run: dotnet publish home.bezard.net.csproj -c Release -o release --nologo
      
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: '/release'
        METHOD: sftp
        PORT: 22
        ARGS: --delete
