on:
  push:
    branches:    
      - master
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
        
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    
    - run: dotnet publish home.bezard.net.csproj -c Release -o release --nologo

    - name: List output files
      run: ls

    - name: FTP-Deploy-Action
      uses: wangyucode/sftp-upload-action@main
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: './release/wwwroot/'
        remoteDir: '/home/baurez/docker/mini-webserver/'
        port: 22
